### ISSUE TITLE
Improve discovering hostname IP address

### ISSUE THREAD

**Issue by banjoh** [epoweripione/docker-vsftpd-alpine#1]
The command below will resolve my computers public IP address instead of the container's IP address when running within a cluster i.e launched using docker-compose file.
```
export PASV_ADDRESS=$(curl -s -4 --connect-timeout 5 --max-time 10 ifconfig.co)
```

I my use case I would like to run an FTP server within a private docker network where only containers in my cluster can access the container.

This command seems to get the correct IP address
```
export PASV_ADDRESS=$(hostname -i)
```

It would be better to have a separate environment variable `PASV_PRIVATE_ADDRESS` or similar which is defined would be used with `$(hostname -i)` instead and take precedence over the current implementation.

**Comment by epoweripione** [comment]
You are right, but you can also pass hostname to container by using `docker-compose.yml` with `PASV_ADDRESS=<hostname or ip>`.

Maybe this is an option solution for you, have fun!

**Comment by banjoh** [comment]
Thanks for the quick response :)

I had tried that earlier with my python client but it did not work since my client is not able to resolve the hostname. I've not taken a closer look though. It's the same error when using ruby.

Adding `pasv_addr_resolve=YES` to `vsftpd.conf` seems to solve my problems. If the server cannot resolve the hostname the server does not start though. Some error handling would be needed if this config is added to the default config.

I'll close this issue for now.
